pull_request_rules:
  - name: automatic merge of new blog post
    conditions:
      - files~=[A-Z][a-z]*[A-z][a-z]*\.Rmd
      - files!=FirstnameLastname\.Rmd
    actions:
      merge:
        method: merge
