pull_request_rules:
  - name: Reject merge of new blog post
    conditions:
      - files~=[\d{2}]/LastnameFirstname\.(rmd|Rmd)
    actions:
      label:
        add: ['modifies-template']
      comment:
        message: You cannot modify the LastnameFirstname.Rmd file. Try again, but only modify the file with your name this time.
  - name: Reject merge of new blog post
    conditions:
      - files~=.gitignore
    actions:
      label:
        add: ['illegal-files']
      comment:
        message: Do not push gitignore files. 
  - name: Reject merge of new blog post
    conditions:
      - files~=.Rproj
    actions:
      label:
        add: ['illegal-files']
      comment:
        message: Do not push Rproject files.
  - name: Reject merge of new blog post
    conditions:
      - files~=.Rprofile
    actions:
      label:
        add: ['illegal-files']
      comment:
        message: Do not push Rprofile files. 
  - name: automatic merge of new blog post
    conditions:
      - files~=[\d{2}]/(Mc)?[A-Z][a-z]{1,}[A-Z][a-z]{1,}\.(Rmd|md|rmd)
      - label!=modifies-template
      - label!=illegal-files
    actions:
      merge:
        method: merge
        strict: true
