pull_request_rules:
  - name: Reject merge of new blog post
    conditions:
      - files~=[\d{2}]/LastnameFirstname\.(Rmd|html)
    actions:
      label:
        add: modifies-template
      comment:
        message: You cannot modify the LastnameFirstname.Rmd file. Try again, but only modify the file with your name this time.
  - name: automatic merge of new blog post
    conditions:
      - files~=[\d{2}]/[A-Z][a-z]{1,}[A-z][a-z]{1,}\.(Rmd|md)
      - label!=modifies-template
    actions:
      merge:
        method: merge
        strict: true
